<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Turnos.aspx.cs" Inherits="Vistas.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style3 {
            width: 320px;
            margin-left: 80px;
            height: 23px;
        }
        .auto-style6 {
            width: 320px;
        }
        .auto-style7 {
            width: 320px;
            height: 23px;
        }
        .auto-style8 {
            width: 320px;
            height: 21px;
        }
        .auto-style9 {
            width: 320px;
            height: 41px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <table class="auto-style1">
            <tr>
                <td class="auto-style6">
                    Usuario Logueado: 
                    <asp:Label ID="lblUsuario" runat="server" Font-Bold="True"></asp:Label>
                    <br />
                    Tipo Usuario:
                    <asp:Label ID="lblTipoUsuario" runat="server" Font-Bold="True"></asp:Label>
                </td>
                <td class="auto-style6">
                    &nbsp;</td>
                <td class="auto-style6">&nbsp;</td>
                <td class="auto-style6">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style7"></td>
                <td class="auto-style7"></td>
                <td class="auto-style7"></td>
                <td class="auto-style7"></td>
            </tr>
            <tr>
                <td class="auto-style7">
                    <asp:HyperLink ID="HyperLink2" runat="server" EnableTheming="False" NavigateUrl="~/Turnos.aspx">Gestion de turnos</asp:HyperLink>
                </td>
                <td class="auto-style7">
                    <asp:HyperLink ID="HyperLink3" runat="server" NavigateUrl="~/Profesionales.aspx">Gestion de profesionales</asp:HyperLink>
                </td>
                <td class="auto-style7">
                    <asp:HyperLink ID="HyperLink4" runat="server" NavigateUrl="~/Pacientes.aspx">Gestion de pacientes</asp:HyperLink>
                </td>
                <td class="auto-style7">
                    <asp:HyperLink ID="HyperLink6" runat="server" NavigateUrl="~/HistoriasClinicas.aspx">Historias Clinicas</asp:HyperLink>
                </td>
            </tr>
            <tr>
                <td class="auto-style9">
                    <asp:HyperLink ID="hpReportes" runat="server" NavigateUrl="~/Reportes.aspx">Reportes</asp:HyperLink>
                </td>
                <td class="auto-style9"></td>
                <td class="auto-style9"></td>
                <td class="auto-style9"></td>
            </tr>
            <tr>
                <td class="auto-style3">
                    <asp:HyperLink ID="HyperLink5" runat="server" NavigateUrl="~/Agregar Turno.aspx">Agregar nuevo turno</asp:HyperLink>
                </td>
                <td class="auto-style7">
                    &nbsp;</td>
                <td class="auto-style7"></td>
                <td class="auto-style7">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style8">
                    </td>
                <td class="auto-style8">&nbsp;</td>
                <td class="auto-style8"></td>
                <td class="auto-style8"></td>
            </tr>
        </table>
        Ingrese codigo del turno:&nbsp; <asp:TextBox ID="txtBuscarTurno" runat="server" Width="86px"></asp:TextBox>
                    &nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnBuscar_Tur" runat="server" Text="Buscar" Width="61px" OnClick="btnBuscar_Tur_Click" />
                <br />
        <br />
        Listado de turnos asignados: 
        <br />
        <br />
                    <asp:GridView ID="grdTurno" runat="server" AutoGenerateDeleteButton="True" AutoGenerteColumns="False" OnRowDeleting="grdTurno_RowDeleting" OnRowCancelingEdit="grdTurno_RowCancelingEdit" OnRowEditing="grdTurno_RowEditing" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" Width="960px">
                        <Columns>
                            <asp:TemplateField HeaderText="Nro Turno">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_tur_nro" runat="server" Text='<%# Bind("Nro_Turno") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Fecha">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_tur_Fecha" runat="server" Text='<%# Bind("Fecha") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nombre Profesional">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_tur_nombreProf" runat="server" Text='<%# Bind("Nombre_Profesional") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Especialidad">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_tur_Especialidad" runat="server" Text='<%# Bind("Especialidad") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nombre Paciente">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_NombrePac" runat="server" Text='<%# Bind("Nombre_Paciente") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="DNI">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_Dni" runat="server" Text='<%# Bind("DNI") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Obra Social">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_ObraSocial" runat="server" Text='<%# Bind("Obra_Social") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Estado">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_Estado" runat="server" Text='<%# Bind("Estado") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lbl_estado" runat="server" Text='<%# Bind("Estado") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="White" ForeColor="#000066" />
                        <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                        <RowStyle ForeColor="#000066" />
                        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#007DBB" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#00547E" />
                    </asp:GridView>
        <br />
        <asp:Panel ID="pnlProfesionales" runat="server" Height="300px">
        </asp:Panel>
    </form>
</body>
</html>
